/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'date' : Time,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'createdAt' : Time,
  'guestName' : string,
  'productId' : bigint,
  'guestEmail' : string,
  'quantity' : bigint,
  'shippingAddress' : string,
  'totalPrice' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string, string, string, string], bigint>,
  'addProduct' : ActorMethod<[string, string, string, number, string], bigint>,
  'applyCouponCode' : ActorMethod<[number, string], number>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'initializeSampleContent' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<
    [string, string, string, bigint, bigint, number],
    bigint
  >,
  'resetData' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];